name: Publish Pre-Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*alpha*'
      - 'v*beta*'
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install pypa/build
        run: python -m pip install build python-dotenv
      - name: Build a binary wheel and a source tarball
        run: |
          echo "$VERSION"
          python -m build
        env:
          VERSION: ${{ github.ref##*/ }}
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: PyOpenProject ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: true