# This is a basic workflow to help you get started with Actions

name: Run Test Cases

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9, 3.8, 3.7, 3.6, 3.5, 2.7 ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        id: dependences
        run: |
          python -m pip install --upgrade pip
          python -m pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Bring test environment up
        id: compose-up
        working-directory: ./tests/infra
        run: |
          docker-compose up -d
          printf 'WAITING FOR APIv3'
          until $(curl --output /dev/null --silent --head --fail http://localhost:8080); do
              printf '.';
              sleep 5;
          done
          printf '\n\n'
          printf '############################\n'
          printf '############################\n'
          printf '####### UP & RUNNING #######\n'
          printf '############################\n'
          printf '############################'
      - name: Run test cases with unittest
        id: run-tests
        run: |
          python -m coverage run -m unittest discover -s ./tests/test_cases -t tests/test_cases -p *_test.py
      - name: Create coverage.xml
        id: coverage-file
        if: steps.run-tests.outcome == 'success' || steps.run-tests.outcome == 'failure'
        run: |
          python -m coverage report -m
          python -m coverage xml
      - name: Run codacy-coverage-reporter
        id: codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
        if: steps.coverage-file.outcome == 'success'
      - name: Bring test environment down
        id: compose-down
        if: steps.compose-up.outcome == 'success'
        working-directory: ./tests/infra
        run: |
          docker-compose down --volumes
